package com.sendspindroid.sendspin.protocol.wire

import com.sendspindroid.sendspin.protocol.JsonOptional
import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Wire-level representations of every Sendspin JSON message we send or receive.
 *
 * These types map 1:1 to the JSON shapes on the wire. Higher-level domain
 * types in `SendSpinProtocol.kt` (TrackMetadata, ControllerState, ColorState,
 * etc.) are derived from these by the message parser, which is where merge-with-
 * previous and legacy-fallback logic lives.
 *
 * Fields that need to distinguish JSON-absent from JSON-null use
 * [JsonOptional]; fields where absent ≡ null use a nullable type with a
 * default of null.
 *
 * All adapters are generated by KSP via moshi-kotlin-codegen; nothing here
 * uses runtime reflection on the audio hot path.
 */

// ── Incoming ──────────────────────────────────────────────────────────────

// Incoming wire types: scalar fields are nullable with `= null` defaults so
// that `present-but-null` JSON does not throw `JsonDataException` from the
// KSP-generated adapter. Defaults are applied at the domain-mapping step.
@JsonClass(generateAdapter = true)
internal data class WireServerHelloPayload(
    @Json(name = "name") val name: String? = null,
    @Json(name = "server_id") val serverId: String? = null,
    @Json(name = "version") val version: Int? = null,
    @Json(name = "active_roles") val activeRoles: List<String>? = null,
    @Json(name = "connection_reason") val connectionReason: String? = null,
)

@JsonClass(generateAdapter = true)
internal data class WireServerTimePayload(
    @Json(name = "client_transmitted") val clientTransmitted: Long? = null,
    @Json(name = "server_received") val serverReceived: Long? = null,
    @Json(name = "server_transmitted") val serverTransmitted: Long? = null,
)

@JsonClass(generateAdapter = true)
internal data class WireServerStatePayload(
    @Json(name = "metadata") val metadata: WireMetadata? = null,
    @Json(name = "state") val state: String? = null,
    @Json(name = "controller") val controller: WireController? = null,
    @Json(name = "color") val color: WireColor? = null,
)

@JsonClass(generateAdapter = true)
internal data class WireMetadata(
    @Json(name = "timestamp") val timestamp: Long? = null,
    @Json(name = "title") val title: JsonOptional<String> = JsonOptional.Absent,
    @Json(name = "artist") val artist: JsonOptional<String> = JsonOptional.Absent,
    @Json(name = "album_artist") val albumArtist: JsonOptional<String> = JsonOptional.Absent,
    @Json(name = "album") val album: JsonOptional<String> = JsonOptional.Absent,
    @Json(name = "artwork_url") val artworkUrl: JsonOptional<String> = JsonOptional.Absent,
    @Json(name = "year") val year: JsonOptional<Int> = JsonOptional.Absent,
    @Json(name = "album_track") val albumTrack: JsonOptional<Int> = JsonOptional.Absent,
    @Json(name = "track") val legacyTrack: JsonOptional<Int> = JsonOptional.Absent,
    @Json(name = "queue_track") val queueTrack: JsonOptional<Int> = JsonOptional.Absent,
    @Json(name = "total_tracks") val totalTracks: JsonOptional<Int> = JsonOptional.Absent,
    @Json(name = "progress") val progress: JsonOptional<WireProgress> = JsonOptional.Absent,
    // Legacy flat progress (pre-nested-progress servers)
    @Json(name = "position_ms") val legacyPositionMs: JsonOptional<Long> = JsonOptional.Absent,
    @Json(name = "duration_ms") val legacyDurationMs: JsonOptional<Long> = JsonOptional.Absent,
    @Json(name = "playback_speed") val legacyPlaybackSpeed: JsonOptional<Int> = JsonOptional.Absent,
    // Legacy controller fields (pre-controller-object servers)
    @Json(name = "repeat") val legacyRepeat: JsonOptional<String> = JsonOptional.Absent,
    @Json(name = "shuffle") val legacyShuffle: JsonOptional<Boolean> = JsonOptional.Absent,
)

@JsonClass(generateAdapter = true)
internal data class WireProgress(
    @Json(name = "track_progress") val trackProgress: Long? = null,
    @Json(name = "track_duration") val trackDuration: Long? = null,
    @Json(name = "playback_speed") val playbackSpeed: Int? = null,
)

@JsonClass(generateAdapter = true)
internal data class WireController(
    @Json(name = "supported_commands") val supportedCommands: List<String>? = null,
    @Json(name = "volume") val volume: Int? = null,
    @Json(name = "muted") val muted: Boolean? = null,
    @Json(name = "repeat") val repeat: JsonOptional<String> = JsonOptional.Absent,
    @Json(name = "shuffle") val shuffle: JsonOptional<Boolean> = JsonOptional.Absent,
)

@JsonClass(generateAdapter = true)
internal data class WireColor(
    @Json(name = "timestamp") val timestamp: Long? = null,
    @Json(name = "background_dark") val backgroundDark: List<Int>? = null,
    @Json(name = "background_light") val backgroundLight: List<Int>? = null,
    @Json(name = "primary") val primary: List<Int>? = null,
    @Json(name = "accent") val accent: List<Int>? = null,
    @Json(name = "on_dark") val onDark: List<Int>? = null,
    @Json(name = "on_light") val onLight: List<Int>? = null,
)

@JsonClass(generateAdapter = true)
internal data class WireStreamStartPayload(
    @Json(name = "player") val player: WireStreamPlayer? = null,
)

@JsonClass(generateAdapter = true)
internal data class WireStreamPlayer(
    @Json(name = "codec") val codec: String? = null,
    @Json(name = "sample_rate") val sampleRate: Int? = null,
    @Json(name = "channels") val channels: Int? = null,
    @Json(name = "bit_depth") val bitDepth: Int? = null,
    @Json(name = "codec_header") val codecHeader: String? = null,
)

@JsonClass(generateAdapter = true)
internal data class WireServerCommandPayload(
    @Json(name = "player") val player: WireServerPlayerCommand? = null,
)

@JsonClass(generateAdapter = true)
internal data class WireServerPlayerCommand(
    @Json(name = "command") val command: String? = null,
    @Json(name = "volume") val volume: Int? = null,
    @Json(name = "mute") val mute: Boolean? = null,
)

@JsonClass(generateAdapter = true)
internal data class WireGroupUpdatePayload(
    @Json(name = "group_id") val groupId: String? = null,
    @Json(name = "group_name") val groupName: String? = null,
    @Json(name = "playback_state") val playbackState: String? = null,
)

@JsonClass(generateAdapter = true)
internal data class WireSyncOffsetPayload(
    @Json(name = "player_id") val playerId: String? = null,
    @Json(name = "offset_ms") val offsetMs: Double? = null,
    @Json(name = "source") val source: String? = null,
)

// Shared `roles` field carried by stream/end and stream/clear. The element
// type is Any? (not String) so a non-string array entry is dropped rather than
// failing the whole decode -- matching the prior raw-cast mapNotNull { it as?
// String } behavior. A missing `roles` key decodes to null ("all roles"); an
// empty array decodes to an empty list.
@JsonClass(generateAdapter = true)
internal data class WireRoles(
    @Json(name = "roles") val roles: List<Any?>? = null,
)

// ── Outgoing ──────────────────────────────────────────────────────────────

@JsonClass(generateAdapter = true)
internal data class WireClientHelloEnvelope(
    @Json(name = "type") val type: String = "client/hello",
    @Json(name = "payload") val payload: WireClientHelloPayload,
)

@JsonClass(generateAdapter = true)
internal data class WireClientHelloPayload(
    @Json(name = "client_id") val clientId: String,
    @Json(name = "name") val name: String,
    @Json(name = "version") val version: Int = 1,
    @Json(name = "supported_roles") val supportedRoles: List<String>,
    @Json(name = "device_info") val deviceInfo: WireDeviceInfo,
    @Json(name = "player@v1_support") val playerSupport: WirePlayerSupport,
    @Json(name = "artwork@v1_support") val artworkSupport: WireArtworkSupport? = null,
    @Json(name = "controller@v1_support") val controllerSupport: Map<String, Any?> = emptyMap(),
    @Json(name = "metadata@v1_support") val metadataSupport: Map<String, Any?> = emptyMap(),
    @Json(name = "color@v1_support") val colorSupport: Map<String, Any?> = emptyMap(),
)

@JsonClass(generateAdapter = true)
internal data class WireDeviceInfo(
    @Json(name = "product_name") val productName: String,
    @Json(name = "manufacturer") val manufacturer: String,
    @Json(name = "software_version") val softwareVersion: String,
)

@JsonClass(generateAdapter = true)
internal data class WirePlayerSupport(
    @Json(name = "supported_formats") val supportedFormats: List<WireAudioFormat>,
    @Json(name = "buffer_capacity") val bufferCapacity: Int,
    @Json(name = "supported_commands") val supportedCommands: List<String> = listOf("volume", "mute"),
)

@JsonClass(generateAdapter = true)
internal data class WireAudioFormat(
    @Json(name = "codec") val codec: String,
    @Json(name = "sample_rate") val sampleRate: Int,
    @Json(name = "channels") val channels: Int,
    @Json(name = "bit_depth") val bitDepth: Int,
)

@JsonClass(generateAdapter = true)
internal data class WireArtworkSupport(
    @Json(name = "channels") val channels: List<WireArtworkChannel>,
)

@JsonClass(generateAdapter = true)
internal data class WireArtworkChannel(
    @Json(name = "source") val source: String,
    @Json(name = "format") val format: String,
    @Json(name = "media_width") val mediaWidth: Int,
    @Json(name = "media_height") val mediaHeight: Int,
)

@JsonClass(generateAdapter = true)
internal data class WireClientTimeEnvelope(
    @Json(name = "type") val type: String = "client/time",
    @Json(name = "payload") val payload: WireClientTimePayload,
)

@JsonClass(generateAdapter = true)
internal data class WireClientTimePayload(
    @Json(name = "client_transmitted") val clientTransmitted: Long,
)

@JsonClass(generateAdapter = true)
internal data class WireClientGoodbyeEnvelope(
    @Json(name = "type") val type: String = "client/goodbye",
    @Json(name = "payload") val payload: WireClientGoodbyePayload,
)

@JsonClass(generateAdapter = true)
internal data class WireClientGoodbyePayload(
    @Json(name = "reason") val reason: String,
)

@JsonClass(generateAdapter = true)
internal data class WireClientStateEnvelope(
    @Json(name = "type") val type: String = "client/state",
    @Json(name = "payload") val payload: WireClientStatePayload,
)

@JsonClass(generateAdapter = true)
internal data class WireClientStatePayload(
    // Top-level `state` is the spec-current location (PR #50).
    @Json(name = "state") val state: String,
    @Json(name = "player") val player: WireClientPlayerState,
)

@JsonClass(generateAdapter = true)
internal data class WireClientPlayerState(
    @Json(name = "state") val state: String,
    @Json(name = "volume") val volume: Int,
    @Json(name = "muted") val muted: Boolean,
    @Json(name = "static_delay_ms") val staticDelayMs: Int,
)

@JsonClass(generateAdapter = true)
internal data class WireClientCommandEnvelope(
    @Json(name = "type") val type: String = "client/command",
    @Json(name = "payload") val payload: WireClientCommandPayload,
)

// ── PROXY-mode auth (not part of the Sendspin spec; specific to the
//    authenticated reverse-proxy transport used on this fork).
@JsonClass(generateAdapter = true)
internal data class WireProxyAuthMessage(
    @Json(name = "type") val type: String = "auth",
    @Json(name = "token") val token: String,
    @Json(name = "client_id") val clientId: String,
)

/**
 * Server response on the proxy auth channel. Successful auth doesn't return
 * anything specific (the server sends a `server/hello` once the connection
 * is accepted); failure messages look like `{"type":"auth_failed","message":"..."}`
 * or `{"type":"error","message":"..."}`.
 */
@JsonClass(generateAdapter = true)
internal data class WireProxyAuthResponse(
    @Json(name = "type") val type: String? = null,
    @Json(name = "message") val message: String? = null,
)

@JsonClass(generateAdapter = true)
internal data class WireClientCommandPayload(
    @Json(name = "controller") val controller: WireClientControllerCommand,
)

@JsonClass(generateAdapter = true)
internal data class WireClientControllerCommand(
    @Json(name = "command") val command: String,
)
